Address clang compiler warnings in PDL 2.082
PDLPorters/pdl pull request #423
Opened 2023-04-11 17:47 UTC by d-lamb

These commits address most, but not all, of the clang compiler warnings that I see with PDL 2.082.  Most have to do with the newly supported datatypes such as (complex) Long Double, and avoids possible truncation-of-value problems.

2023-04-11 17:52 UTC, mohawk2 commented
Thank you for this! I did see the notifications on the IRC channel you'd pushed to this branch, and already took a look.

Some of these changes are a really good idea, and I am about to cherry-pick them straight onto `master`, so I'll also rebase past those in a moment and force-push. I have comments about the others, but first things first!

2023-04-11 18:05 UTC, mohawk2 commented on Basic/Core/pdlcore.c
> +	return ((s*181)*((pid-83)*359))%104729;
I had to check but you (and clang) are quite correct, that unsigned arithmetic always wraps, so thank you. Pushing this to `master`.

2023-04-11 19:59 UTC, mohawk2 requested changes
The one remaining change for this (making a complete copy of `cfunc` with one change) is slightly problematic, for two reasons:
- I'm not convinced it's done in the right way: C99 (which we require for exactly this, complex numbers) defines that `tgmath` supports `fabs` for complex numbers including `complex long double`: https://en.cppreference.com/w/c/numeric/tgmath
- Copy-paste programming creates problems for future maintainers; if this change *were* necessary, far better to do it by adding arguments to something, similar to the `NoTgmath` in `ufunc`

Could you try instead replacing this line:

`cfunc('_cabs', 'cabs', 1, 'Returns the absolute (length) of a complex number.', undef,`

so the second argument is `fabs`, and delete the `cfuncl` stuff, and see what clang says?

2023-04-12 02:57 UTC, d-lamb commented
Essentially undoing my original commit to ops.pd and making the change you suggested (`cabs` -> `fabs` in that one line) causes no additional clang warnings, and passes `make test`.  It's fine with me if you want to just drop the one remaining commit here on the floor and make that change directly in master.

2023-04-12 03:22 UTC, merged

2023-04-12 03:25 UTC, mohawk2 commented
I instead adjusted your commit to do this (which had the additional benefit of leaving all the other `cfunc` users with `complex long double`), and have now merged it. Thank you!